// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/documentation.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "google/api/Documentation.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GAPIDocumentationRoot

@implementation GAPIDocumentationRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - GAPIDocumentationRoot_FileDescriptor

static GPBFileDescriptor *GAPIDocumentationRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.api"
                                                 objcPrefix:@"GAPI"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GAPIDocumentation

@implementation GAPIDocumentation

@dynamic summary;
@dynamic pagesArray, pagesArray_Count;
@dynamic rulesArray, rulesArray_Count;
@dynamic documentationRootURL;
@dynamic overview;

typedef struct GAPIDocumentation__storage_ {
  uint32_t _has_storage_[1];
  NSString *summary;
  NSString *overview;
  NSMutableArray *rulesArray;
  NSString *documentationRootURL;
  NSMutableArray *pagesArray;
} GAPIDocumentation__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "summary",
        .dataTypeSpecific.className = NULL,
        .number = GAPIDocumentation_FieldNumber_Summary,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GAPIDocumentation__storage_, summary),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "overview",
        .dataTypeSpecific.className = NULL,
        .number = GAPIDocumentation_FieldNumber_Overview,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GAPIDocumentation__storage_, overview),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "rulesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GAPIDocumentationRule),
        .number = GAPIDocumentation_FieldNumber_RulesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPIDocumentation__storage_, rulesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "documentationRootURL",
        .dataTypeSpecific.className = NULL,
        .number = GAPIDocumentation_FieldNumber_DocumentationRootURL,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GAPIDocumentation__storage_, documentationRootURL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pagesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GAPIPage),
        .number = GAPIDocumentation_FieldNumber_PagesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPIDocumentation__storage_, pagesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GAPIDocumentation class]
                                     rootClass:[GAPIDocumentationRoot class]
                                          file:GAPIDocumentationRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GAPIDocumentation__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\004\r\244\241!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GAPIDocumentationRule

@implementation GAPIDocumentationRule

@dynamic selector;
@dynamic description_p;
@dynamic deprecationDescription;

typedef struct GAPIDocumentationRule__storage_ {
  uint32_t _has_storage_[1];
  NSString *selector;
  NSString *description_p;
  NSString *deprecationDescription;
} GAPIDocumentationRule__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "selector",
        .dataTypeSpecific.className = NULL,
        .number = GAPIDocumentationRule_FieldNumber_Selector,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GAPIDocumentationRule__storage_, selector),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "description_p",
        .dataTypeSpecific.className = NULL,
        .number = GAPIDocumentationRule_FieldNumber_Description_p,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GAPIDocumentationRule__storage_, description_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deprecationDescription",
        .dataTypeSpecific.className = NULL,
        .number = GAPIDocumentationRule_FieldNumber_DeprecationDescription,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GAPIDocumentationRule__storage_, deprecationDescription),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GAPIDocumentationRule class]
                                     rootClass:[GAPIDocumentationRoot class]
                                          file:GAPIDocumentationRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GAPIDocumentationRule__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GAPIPage

@implementation GAPIPage

@dynamic name;
@dynamic content;
@dynamic subpagesArray, subpagesArray_Count;

typedef struct GAPIPage__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSString *content;
  NSMutableArray *subpagesArray;
} GAPIPage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = GAPIPage_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GAPIPage__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = GAPIPage_FieldNumber_Content,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GAPIPage__storage_, content),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "subpagesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GAPIPage),
        .number = GAPIPage_FieldNumber_SubpagesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPIPage__storage_, subpagesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GAPIPage class]
                                     rootClass:[GAPIDocumentationRoot class]
                                          file:GAPIDocumentationRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GAPIPage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
