// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/logging.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "google/api/Logging.pbobjc.h"
 #import "google/api/Annotations.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GAPILoggingRoot

@implementation GAPILoggingRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    registry = [[GPBExtensionRegistry alloc] init];
    // Merge in the imports (direct or indirect) that defined extensions.
    [registry addExtensions:[GAPIAnnotationsRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GAPILoggingRoot_FileDescriptor

static GPBFileDescriptor *GAPILoggingRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.api"
                                                 objcPrefix:@"GAPI"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GAPILogging

@implementation GAPILogging

@dynamic producerDestinationsArray, producerDestinationsArray_Count;
@dynamic consumerDestinationsArray, consumerDestinationsArray_Count;

typedef struct GAPILogging__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *producerDestinationsArray;
  NSMutableArray *consumerDestinationsArray;
} GAPILogging__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "producerDestinationsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GAPILogging_LoggingDestination),
        .number = GAPILogging_FieldNumber_ProducerDestinationsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPILogging__storage_, producerDestinationsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "consumerDestinationsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GAPILogging_LoggingDestination),
        .number = GAPILogging_FieldNumber_ConsumerDestinationsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPILogging__storage_, consumerDestinationsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GAPILogging class]
                                     rootClass:[GAPILoggingRoot class]
                                          file:GAPILoggingRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GAPILogging__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GAPILogging_LoggingDestination

@implementation GAPILogging_LoggingDestination

@dynamic monitoredResource;
@dynamic logsArray, logsArray_Count;

typedef struct GAPILogging_LoggingDestination__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *logsArray;
  NSString *monitoredResource;
} GAPILogging_LoggingDestination__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "logsArray",
        .dataTypeSpecific.className = NULL,
        .number = GAPILogging_LoggingDestination_FieldNumber_LogsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPILogging_LoggingDestination__storage_, logsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "monitoredResource",
        .dataTypeSpecific.className = NULL,
        .number = GAPILogging_LoggingDestination_FieldNumber_MonitoredResource,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GAPILogging_LoggingDestination__storage_, monitoredResource),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GAPILogging_LoggingDestination class]
                                     rootClass:[GAPILoggingRoot class]
                                          file:GAPILoggingRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GAPILogging_LoggingDestination__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    [localDescriptor setupContainingMessageClassName:GPBStringifySymbol(GAPILogging)];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
