// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/monitoring.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "google/api/Monitoring.pbobjc.h"
 #import "google/api/Annotations.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GAPIMonitoringRoot

@implementation GAPIMonitoringRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    registry = [[GPBExtensionRegistry alloc] init];
    // Merge in the imports (direct or indirect) that defined extensions.
    [registry addExtensions:[GAPIAnnotationsRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GAPIMonitoringRoot_FileDescriptor

static GPBFileDescriptor *GAPIMonitoringRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.api"
                                                 objcPrefix:@"GAPI"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GAPIMonitoring

@implementation GAPIMonitoring

@dynamic producerDestinationsArray, producerDestinationsArray_Count;
@dynamic consumerDestinationsArray, consumerDestinationsArray_Count;

typedef struct GAPIMonitoring__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *producerDestinationsArray;
  NSMutableArray *consumerDestinationsArray;
} GAPIMonitoring__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "producerDestinationsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GAPIMonitoring_MonitoringDestination),
        .number = GAPIMonitoring_FieldNumber_ProducerDestinationsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPIMonitoring__storage_, producerDestinationsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "consumerDestinationsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GAPIMonitoring_MonitoringDestination),
        .number = GAPIMonitoring_FieldNumber_ConsumerDestinationsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPIMonitoring__storage_, consumerDestinationsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GAPIMonitoring class]
                                     rootClass:[GAPIMonitoringRoot class]
                                          file:GAPIMonitoringRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GAPIMonitoring__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GAPIMonitoring_MonitoringDestination

@implementation GAPIMonitoring_MonitoringDestination

@dynamic monitoredResource;
@dynamic metricsArray, metricsArray_Count;

typedef struct GAPIMonitoring_MonitoringDestination__storage_ {
  uint32_t _has_storage_[1];
  NSString *monitoredResource;
  NSMutableArray *metricsArray;
} GAPIMonitoring_MonitoringDestination__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "monitoredResource",
        .dataTypeSpecific.className = NULL,
        .number = GAPIMonitoring_MonitoringDestination_FieldNumber_MonitoredResource,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GAPIMonitoring_MonitoringDestination__storage_, monitoredResource),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "metricsArray",
        .dataTypeSpecific.className = NULL,
        .number = GAPIMonitoring_MonitoringDestination_FieldNumber_MetricsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GAPIMonitoring_MonitoringDestination__storage_, metricsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GAPIMonitoring_MonitoringDestination class]
                                     rootClass:[GAPIMonitoringRoot class]
                                          file:GAPIMonitoringRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GAPIMonitoring_MonitoringDestination__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    [localDescriptor setupContainingMessageClassName:GPBStringifySymbol(GAPIMonitoring)];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
