// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/monitoring.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GAPIMonitoring_MonitoringDestination;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GAPIMonitoringRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GAPIMonitoringRoot : GPBRootObject
@end

#pragma mark - GAPIMonitoring

typedef GPB_ENUM(GAPIMonitoring_FieldNumber) {
  GAPIMonitoring_FieldNumber_ProducerDestinationsArray = 1,
  GAPIMonitoring_FieldNumber_ConsumerDestinationsArray = 2,
};

/**
 * Monitoring configuration of the service.
 *
 * The example below shows how to configure monitored resources and metrics
 * for monitoring. In the example, a monitored resource and two metrics are
 * defined. The `library.googleapis.com/book/returned_count` metric is sent
 * to both producer and consumer projects, whereas the
 * `library.googleapis.com/book/overdue_count` metric is only sent to the
 * consumer project.
 *
 *     monitored_resources:
 *     - type: library.googleapis.com/branch
 *       labels:
 *       - key: /city
 *         description: The city where the library branch is located in.
 *       - key: /name
 *         description: The name of the branch.
 *     metrics:
 *     - name: library.googleapis.com/book/returned_count
 *       metric_kind: DELTA
 *       value_type: INT64
 *       labels:
 *       - key: /customer_id
 *     - name: library.googleapis.com/book/overdue_count
 *       metric_kind: GAUGE
 *       value_type: INT64
 *       labels:
 *       - key: /customer_id
 *     monitoring:
 *       producer_destinations:
 *       - monitored_resource: library.googleapis.com/branch
 *         metrics:
 *         - library.googleapis.com/book/returned_count
 *       consumer_destinations:
 *       - monitored_resource: library.googleapis.com/branch
 *         metrics:
 *         - library.googleapis.com/book/returned_count
 *         - library.googleapis.com/book/overdue_count
 **/
@interface GAPIMonitoring : GPBMessage

/**
 * Monitoring configurations for sending metrics to the producer project.
 * There can be multiple producer destinations, each one must have a
 * different monitored resource type. A metric can be used in at most
 * one producer destination.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GAPIMonitoring_MonitoringDestination*> *producerDestinationsArray;
/** The number of items in @c producerDestinationsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger producerDestinationsArray_Count;

/**
 * Monitoring configurations for sending metrics to the consumer project.
 * There can be multiple consumer destinations, each one must have a
 * different monitored resource type. A metric can be used in at most
 * one consumer destination.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GAPIMonitoring_MonitoringDestination*> *consumerDestinationsArray;
/** The number of items in @c consumerDestinationsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger consumerDestinationsArray_Count;

@end

#pragma mark - GAPIMonitoring_MonitoringDestination

typedef GPB_ENUM(GAPIMonitoring_MonitoringDestination_FieldNumber) {
  GAPIMonitoring_MonitoringDestination_FieldNumber_MonitoredResource = 1,
  GAPIMonitoring_MonitoringDestination_FieldNumber_MetricsArray = 2,
};

/**
 * Configuration of a specific monitoring destination (the producer project
 * or the consumer project).
 **/
@interface GAPIMonitoring_MonitoringDestination : GPBMessage

/**
 * The monitored resource type. The type must be defined in
 * [Service.monitored_resources][google.api.Service.monitored_resources] section.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *monitoredResource;

/**
 * Names of the metrics to report to this monitoring destination.
 * Each name must be defined in [Service.metrics][google.api.Service.metrics] section.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *metricsArray;
/** The number of items in @c metricsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger metricsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
