// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/system_parameter.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GAPISystemParameter;
@class GAPISystemParameterRule;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GAPISystemParameterRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GAPISystemParameterRoot : GPBRootObject
@end

#pragma mark - GAPISystemParameters

typedef GPB_ENUM(GAPISystemParameters_FieldNumber) {
  GAPISystemParameters_FieldNumber_RulesArray = 1,
};

/**
 * ### System parameter configuration
 *
 * A system parameter is a special kind of parameter defined by the API
 * system, not by an individual API. It is typically mapped to an HTTP header
 * and/or a URL query parameter. This configuration specifies which methods
 * change the names of the system parameters.
 **/
@interface GAPISystemParameters : GPBMessage

/**
 * Define system parameters.
 *
 * The parameters defined here will override the default parameters
 * implemented by the system. If this field is missing from the service
 * config, default system parameters will be used. Default system parameters
 * and names is implementation-dependent.
 *
 * Example: define api key for all methods
 *
 *     system_parameters
 *       rules:
 *         - selector: "*"
 *           parameters:
 *             - name: api_key
 *               url_query_parameter: api_key
 *
 *
 * Example: define 2 api key names for a specific method.
 *
 *     system_parameters
 *       rules:
 *         - selector: "/ListShelves"
 *           parameters:
 *             - name: api_key
 *               http_header: Api-Key1
 *             - name: api_key
 *               http_header: Api-Key2
 *
 * **NOTE:** All service configuration rules follow "last one wins" order.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GAPISystemParameterRule*> *rulesArray;
/** The number of items in @c rulesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rulesArray_Count;

@end

#pragma mark - GAPISystemParameterRule

typedef GPB_ENUM(GAPISystemParameterRule_FieldNumber) {
  GAPISystemParameterRule_FieldNumber_Selector = 1,
  GAPISystemParameterRule_FieldNumber_ParametersArray = 2,
};

/**
 * Define a system parameter rule mapping system parameter definitions to
 * methods.
 **/
@interface GAPISystemParameterRule : GPBMessage

/**
 * Selects the methods to which this rule applies. Use '*' to indicate all
 * methods in all APIs.
 *
 * Refer to [selector][google.api.DocumentationRule.selector] for syntax details.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *selector;

/**
 * Define parameters. Multiple names may be defined for a parameter.
 * For a given method call, only one of them should be used. If multiple
 * names are used the behavior is implementation-dependent.
 * If none of the specified names are present the behavior is
 * parameter-dependent.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GAPISystemParameter*> *parametersArray;
/** The number of items in @c parametersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger parametersArray_Count;

@end

#pragma mark - GAPISystemParameter

typedef GPB_ENUM(GAPISystemParameter_FieldNumber) {
  GAPISystemParameter_FieldNumber_Name = 1,
  GAPISystemParameter_FieldNumber_HTTPHeader = 2,
  GAPISystemParameter_FieldNumber_URLQueryParameter = 3,
};

/**
 * Define a parameter's name and location. The parameter may be passed as either
 * an HTTP header or a URL query parameter, and if both are passed the behavior
 * is implementation-dependent.
 **/
@interface GAPISystemParameter : GPBMessage

/** Define the name of the parameter, such as "api_key" . It is case sensitive. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * Define the HTTP header name to use for the parameter. It is case
 * insensitive.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *HTTPHeader;

/**
 * Define the URL query parameter name to use for the parameter. It is case
 * sensitive.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *URLQueryParameter;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
