// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/usage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GAPIUsageRule;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GAPIUsageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GAPIUsageRoot : GPBRootObject
@end

#pragma mark - GAPIUsage

typedef GPB_ENUM(GAPIUsage_FieldNumber) {
  GAPIUsage_FieldNumber_RequirementsArray = 1,
  GAPIUsage_FieldNumber_RulesArray = 6,
  GAPIUsage_FieldNumber_ProducerNotificationChannel = 7,
};

/**
 * Configuration controlling usage of a service.
 **/
@interface GAPIUsage : GPBMessage

/**
 * Requirements that must be satisfied before a consumer project can use the
 * service. Each requirement is of the form <service.name>/<requirement-id>;
 * for example 'serviceusage.googleapis.com/billing-enabled'.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *requirementsArray;
/** The number of items in @c requirementsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger requirementsArray_Count;

/**
 * A list of usage rules that apply to individual API methods.
 *
 * **NOTE:** All service configuration rules follow "last one wins" order.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GAPIUsageRule*> *rulesArray;
/** The number of items in @c rulesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rulesArray_Count;

/**
 * The full resource name of a channel used for sending notifications to the
 * service producer.
 *
 * Google Service Management currently only supports
 * [Google Cloud Pub/Sub](https://cloud.google.com/pubsub) as a notification
 * channel. To use Google Cloud Pub/Sub as the channel, this must be the name
 * of a Cloud Pub/Sub topic that uses the Cloud Pub/Sub topic name format
 * documented in https://cloud.google.com/pubsub/docs/overview.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *producerNotificationChannel;

@end

#pragma mark - GAPIUsageRule

typedef GPB_ENUM(GAPIUsageRule_FieldNumber) {
  GAPIUsageRule_FieldNumber_Selector = 1,
  GAPIUsageRule_FieldNumber_AllowUnregisteredCalls = 2,
};

/**
 * Usage configuration rules for the service.
 *
 * NOTE: Under development.
 *
 *
 * Use this rule to configure unregistered calls for the service. Unregistered
 * calls are calls that do not contain consumer project identity.
 * (Example: calls that do not contain an API key).
 * By default, API methods do not allow unregistered calls, and each method call
 * must be identified by a consumer project identity. Use this rule to
 * allow/disallow unregistered calls.
 *
 * Example of an API that wants to allow unregistered calls for entire service.
 *
 *     usage:
 *       rules:
 *       - selector: "*"
 *         allow_unregistered_calls: true
 *
 * Example of a method that wants to allow unregistered calls.
 *
 *     usage:
 *       rules:
 *       - selector: "google.example.library.v1.LibraryService.CreateBook"
 *         allow_unregistered_calls: true
 **/
@interface GAPIUsageRule : GPBMessage

/**
 * Selects the methods to which this rule applies. Use '*' to indicate all
 * methods in all APIs.
 *
 * Refer to [selector][google.api.DocumentationRule.selector] for syntax details.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *selector;

/** True, if the method allows unregistered calls; false otherwise. */
@property(nonatomic, readwrite) BOOL allowUnregisteredCalls;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
