// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/color.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/Wrappers.pbobjc.h>
#else
 #import "google/protobuf/Wrappers.pbobjc.h"
#endif

 #import "google/type/Color.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GTPColorRoot

@implementation GTPColorRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - GTPColorRoot_FileDescriptor

static GPBFileDescriptor *GTPColorRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.type"
                                                 objcPrefix:@"GTP"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GTPColor

@implementation GTPColor

@dynamic red;
@dynamic green;
@dynamic blue;
@dynamic hasAlpha, alpha;

typedef struct GTPColor__storage_ {
  uint32_t _has_storage_[1];
  float red;
  float green;
  float blue;
  GPBFloatValue *alpha;
} GTPColor__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "red",
        .dataTypeSpecific.className = NULL,
        .number = GTPColor_FieldNumber_Red,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GTPColor__storage_, red),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "green",
        .dataTypeSpecific.className = NULL,
        .number = GTPColor_FieldNumber_Green,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GTPColor__storage_, green),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "blue",
        .dataTypeSpecific.className = NULL,
        .number = GTPColor_FieldNumber_Blue,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GTPColor__storage_, blue),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "alpha",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBFloatValue),
        .number = GTPColor_FieldNumber_Alpha,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GTPColor__storage_, alpha),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GTPColor class]
                                     rootClass:[GTPColorRoot class]
                                          file:GTPColorRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GTPColor__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
