// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/date.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GTPDateRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GTPDateRoot : GPBRootObject
@end

#pragma mark - GTPDate

typedef GPB_ENUM(GTPDate_FieldNumber) {
  GTPDate_FieldNumber_Year = 1,
  GTPDate_FieldNumber_Month = 2,
  GTPDate_FieldNumber_Day = 3,
};

/**
 * Represents a whole calendar date, e.g. date of birth. The time of day and
 * time zone are either specified elsewhere or are not significant. The date
 * is relative to the Proleptic Gregorian Calendar. The day may be 0 to
 * represent a year and month where the day is not significant, e.g. credit card
 * expiration date. The year may be 0 to represent a month and day independent
 * of year, e.g. anniversary date. Related types are [google.type.TimeOfDay][google.type.TimeOfDay]
 * and `google.protobuf.Timestamp`.
 **/
@interface GTPDate : GPBMessage

/**
 * Year of date. Must be from 1 to 9999, or 0 if specifying a date without
 * a year.
 **/
@property(nonatomic, readwrite) int32_t year;

/** Month of year. Must be from 1 to 12. */
@property(nonatomic, readwrite) int32_t month;

/**
 * Day of month. Must be from 1 to 31 and valid for the year and month, or 0
 * if specifying a year/month where the day is not significant.
 **/
@property(nonatomic, readwrite) int32_t day;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
