// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/dayofweek.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GTPDayOfWeek

/** Represents a day of week. */
typedef GPB_ENUM(GTPDayOfWeek) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GTPDayOfWeek_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** The unspecified day-of-week. */
  GTPDayOfWeek_DayOfWeekUnspecified = 0,

  /** The day-of-week of Monday. */
  GTPDayOfWeek_Monday = 1,

  /** The day-of-week of Tuesday. */
  GTPDayOfWeek_Tuesday = 2,

  /** The day-of-week of Wednesday. */
  GTPDayOfWeek_Wednesday = 3,

  /** The day-of-week of Thursday. */
  GTPDayOfWeek_Thursday = 4,

  /** The day-of-week of Friday. */
  GTPDayOfWeek_Friday = 5,

  /** The day-of-week of Saturday. */
  GTPDayOfWeek_Saturday = 6,

  /** The day-of-week of Sunday. */
  GTPDayOfWeek_Sunday = 7,
};

GPBEnumDescriptor *GTPDayOfWeek_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GTPDayOfWeek_IsValidValue(int32_t value);

#pragma mark - GTPDayofweekRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GTPDayofweekRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
