// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/timeofday.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "google/type/Timeofday.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GTPTimeofdayRoot

@implementation GTPTimeofdayRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - GTPTimeofdayRoot_FileDescriptor

static GPBFileDescriptor *GTPTimeofdayRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"google.type"
                                                 objcPrefix:@"GTP"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GTPTimeOfDay

@implementation GTPTimeOfDay

@dynamic hours;
@dynamic minutes;
@dynamic seconds;
@dynamic nanos;

typedef struct GTPTimeOfDay__storage_ {
  uint32_t _has_storage_[1];
  int32_t hours;
  int32_t minutes;
  int32_t seconds;
  int32_t nanos;
} GTPTimeOfDay__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "hours",
        .dataTypeSpecific.className = NULL,
        .number = GTPTimeOfDay_FieldNumber_Hours,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GTPTimeOfDay__storage_, hours),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "minutes",
        .dataTypeSpecific.className = NULL,
        .number = GTPTimeOfDay_FieldNumber_Minutes,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GTPTimeOfDay__storage_, minutes),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "seconds",
        .dataTypeSpecific.className = NULL,
        .number = GTPTimeOfDay_FieldNumber_Seconds,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GTPTimeOfDay__storage_, seconds),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "nanos",
        .dataTypeSpecific.className = NULL,
        .number = GTPTimeOfDay_FieldNumber_Nanos,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GTPTimeOfDay__storage_, nanos),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GTPTimeOfDay class]
                                     rootClass:[GTPTimeofdayRoot class]
                                          file:GTPTimeofdayRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GTPTimeOfDay__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
